# Generated by Django 4.2.3 on 2023-11-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splid_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='expence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenseDate', models.DateField(auto_now=True)),
                ('expenseTitle', models.CharField(max_length=25)),
                ('expenseAmount', models.IntegerField(default=0)),
                ('expenseBy', models.CharField(max_length=30)),
            ],
        ),
    ]
