# Generated by Django 4.2.3 on 2023-11-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splid_app', '0003_alter_expence_expenseamount_alter_expence_expenseby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
